name: Run example.sh on push to master

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to home directory
        run: cd /home/ubuntu

      - name: Make script executable
        run: chmod +x example.sh

      - name: Run script
        run: ./example.sh
