name: Run build.sh

on:
  workflow_dispatch:  # This triggers the workflow manually

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Run build.sh
        run: |
          bash /home/ubuntu/build.sh

