name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo su -
            cd /home/ubuntu/artisan-node-backend
            git pull
            npm install
            npm start
